---
- name: Install Maven on Jenkins Slave
  hosts: jenkins-slave
  become: true
  tasks:
    - name: Update Package Cache
      apt:
        update_cache: yes

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jre
        state: present

    - name: Download and Extract Maven
      get_url:
        url: "https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz"
        dest: /opt

    - name: Extract Maven Archive
      unarchive:
        src: /opt/apache-maven-3.9.4-bin.tar.gz
        dest: /opt
        creates: /opt/apache-maven-3.9.4
        remote_src: yes
    
    - name: Docker installation
      apt:
        name: Docker
        state: present
        


